server:
  port: 8085
spring:
  application:
    name: smallflyleg
  datasource:
    url: jdbc:mysql://localhost:3306/small
    username: root
    password: root

# mybatisplus
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #表前缀
    table-prefix: sf_
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.smallflyingleg.sso.pojo



eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
#    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
#    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: localhost
    instance-id: ${spring.application.name}:${server.port}